### ISSUE TITLE
Pin code error

### ISSUE THREAD

**Issue by AlexxyQQ** [dineshtiwari69/HamroShare#1]
if the pin code is less then 1000 i,e 0999 it shows pop up error

https://github.com/dineshtiwari69/HamroShare/blob/main/src/Pages/AddAccount.js 
line no: 123
![image](https://user-images.githubusercontent.com/83905037/172548221-cc070477-2bf6-46ba-a5af-f17622f6e124.png)

**Comment by dineshtiwari69** [comment]
Nice Catch , Thankyou it has been fixed 👍 
[https://github.com/dineshtiwari69/HamroShare/commit/7e674ebb5f929c4a72f99b06e3e8834031030802](https://github.com/dineshtiwari69/HamroShare/commit/7e674ebb5f929c4a72f99b06e3e8834031030802) #
