### ISSUE TITLE
Couldn't add accounts from Civil bank after merger with Himalayan Bank. 

### ISSUE THREAD

**Issue by dal1e** [dineshtiwari69/HamroShare#3]
I couldn't add  Civil bank after merger with Himalayan Bank.  Previously I could add it and  was working fine. I had noticed a change in Mero share after the merge. The Bank name has been changed to "Himalayan Bank" while applying IPO. All other details are as it is that includes Capital name.

**Comment by dineshtiwari69** [comment]
Thanks for creating this issue. I will check on with Meroshare for capital api and will update it if anything's changed.

**Comment by dineshtiwari69** [comment]
Is the issue with applying an IPO or with adding accounts?

**Comment by dal1e** [comment]
Adding accounts. Without saved account, I couldn't apply IPO.

**Comment by dineshtiwari69** [comment]
Hamroshare had a complete rewrite from scratch . Hope that resolved the issue. @dal1e
